### ISSUE TITLE
Evaluate NamedThing semantic annotation with skohub example

### ISSUE THREAD

**Issue by GertjanBisschop** [eu-parc/matrix-vocabulary#24]
Given an example of a term within the vocabulary:
```
- aggregation_target: false
  id: https://w3id.org/peh/MA-44bff383cf
  label: atn
  name: All toe nail
  parent_matrix: https://w3id.org/peh/MA-7b8b965ad4
  sort_order: 17
  translations:
  - language: nl-be
    property_name: name
    translated_value: alle teennagels
  unique_name: atn
```
Skohub would list this item as `atn` within the vocabulary as `label` is the `skos:prefLabel`. This does not seem particularly useful for anyone browsing the vocabulary.
It seems much more relevant to me to browse based on the `name` in this case. What needs to change here? 
- semantic annotation of `label` and `name`
- content of these fields
- my understanding of what is useful to use as a displayed name in a vocabulary <- most likely
